name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          version: "2.4.1"

      - name: Build package
        run: |
          poetry install --no-interaction
          poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
